sim_rate: 250
init:
  joint_names: ['left_e0', 'left_e1', 'left_s0', 'left_s1', 'left_w0', 'left_w1', 'left_w2', 'right_e0', 'right_e1', 'right_s0', 'right_s1', 'right_w0', 'right_w1', 'right_w2']
  joint_positions: [0.021992243465574823, 2.0142088438059567, -0.1640957434902317, -0.4838849829428087, -0.9483611749910477, 1.6095009397421718, -0.046057746475481665, -0.019762668025938623, 2.0047272197755603, 0.16697240015086656, -0.4800026258719887, 0.9520902679944943, 1.6110116087474307, 0.05179504840401794]
